### ISSUE TITLE
problem with reconnecting when existing database is present

### ISSUE THREAD

**Issue by bblumberg** [mcollina/aedes-persistence-level#5] opened 2016-05-31 16:04 UTC
Hi

I have attached  a zip file that demonstrates an issue that only appears with aedes-persistence-level (aedes-persistence and aedes-persistence-redis work just fine). Under certain conditions you will get on reconnection (duplication steps and more details are in the zip file:

client error test_client_sink_8247 no such packet Error: no such packet
    at /data/users/bblumberg/Projects/aedes-broker/node_modules/aedes-persistence-level/persistence.js:225:10
    at dispatchError (/data/users/bblumberg/Projects/aedes-broker/node_modules/levelup/lib/util.js:64:35)
    at /data/users/bblumberg/Projects/aedes-broker/node_modules/levelup/lib/levelup.js:222:14

[aedes-issue.zip](https://github.com/mcollina/aedes-persistence-level/files/291562/aedes-issue.zip)

I realize you are working on other stuff now, and may be low priority. Since both persistence and persistence-redis work for me, this is more to help you find what may be a bug in the persistence-level implementation when and if this is becomes a priority.

aedes with aedes-persistence is blindingly fast and places a very modest burden on node. WOW!!!! 

Thanks, bruce

**Comment by mcollina** [comment] 2016-06-04 07:23
The question is that why this does not happen on Redis :).
If you have time, can you investigate in how to reproduce it programmatically?

**Comment by bblumberg** [comment] 2016-06-04 18:55
Sure, I will see what I can find.

I have a feeling it could be a timing issue of some sort, because I wrote a
simpler test case where you can see the error immediately with a clean
database and you get the trace below. As you will note, it clears up after
a few reconnects... I have also attached a copy of the client.

As always, thanks for your help and your great work!!!

bb

node aedes.js
server listening on port 1884
 client connected: tester30826
 client:  no id publishing: tester30826 on topic $SYS/SyXS7je4/new/clients
client error tester30826 no such packet Error: no such packet
    at
/data/users/bblumberg/Projects/aedes-broker/node_modules/aedes-persistence-level/persistence.js:225:10
    at dispatchError
(/data/users/bblumberg/Projects/aedes-broker/node_modules/levelup/lib/util.js:64:35)
    at
/data/users/bblumberg/Projects/aedes-broker/node_modules/levelup/lib/levelup.js:222:14
 client: tester30826 subcribing to: [
 {
  "topic": "workcell/#",
  "qos": 1
 }
]
 client: tester30826 unsubscribing from: [
 "workcell/#"
]
 client disconnected: tester30826
 client:  no id publishing: offline on topic workcell/tester30826/status
 client connected: tester30826
 client:  no id publishing: tester30826 on topic $SYS/SyXS7je4/new/clients
client error tester30826 no such packet Error: no such packet
    at
/data/users/bblumberg/Projects/aedes-broker/node_modules/aedes-persistence-level/persistence.js:225:10
    at dispatchError
(/data/users/bblumberg/Projects/aedes-broker/node_modules/levelup/lib/util.js:64:35)
    at
/data/users/bblumberg/Projects/aedes-broker/node_modules/levelup/lib/levelup.js:222:14
 client: tester30826 subcribing to: [
 {
  "topic": "workcell/#",
  "qos": 1
 }
]
 client: tester30826 unsubscribing from: [
 "workcell/#"
]
 client disconnected: tester30826
 client:  no id publishing: offline on topic workcell/tester30826/status
 client connected: tester30826
 client:  no id publishing: tester30826 on topic $SYS/SyXS7je4/new/clients
 client: tester30826 publishing:
{"item":{"type":"int","value":0,"time":"2016-06-04T18:51:45.965Z"}} on
topic workcell/tester30826/variable/win
 client: tester30826 subcribing to: [
 {
  "topic": "workcell/#",
  "qos": 1
 }
]
 client: tester30826 publishing:
{"item":{"type":"int","value":1,"time":"2016-06-04T18:51:46.448Z"}} on
topic workcell/tester30826/variable/win

On Sat, Jun 4, 2016 at 3:23 AM, Matteo Collina notifications@github.com
wrote:

> The question is that why this does not happen on Redis :).
> If you have time, can you investigate in how to reproduce it
> programmatically?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/mcollina/aedes-persistence-level/issues/5#issuecomment-223741583,
> or mute the thread
> https://github.com/notifications/unsubscribe/AGz5aodS9GK8FPirwLOWNqOYTTbm7rh5ks5qISfsgaJpZM4IqsVk
> .

## 

_. *_.\* _._
- Bruce Blumberg *|  Principal Software Engineer
  *Rethink Robotics, Inc *
  main: 617.500.2487  | cell: 978.430.2206

**Comment by mcollina** [comment] 2016-06-04 19:28
Sorry, I'm missing something. It seems the tester spawns a lot of clients and sends a lot of messages. Can you reproduce it only with a single client (please paste it here in case)?

Yes, it's probably due to some weird condition, but the current logic is sound.

**Comment by bblumberg** [comment] 2016-06-04 21:25
Hi

Yes, I can reproduce it with a single client. Here is the code and I have
attached it and the code for the broker that I am using...

Thanks again,

bb

/**
- Created by bblumberg on 6/4/16.
  */
  'use strict'
  var cluster = require('cluster');
  var mqtt    = require('mqtt');
  var id = 0;
  var client = null;
  var stopPublishing =false;

let i = 0;
  id++;
  var clientId = 'tester' + process.pid;

  var lwt = {
    topic: 'workcell/' + clientId + '/status',
    payload: 'offline',
    qos: 1,
    retain: true
  };

  var connect_options = {
    keepalive: 6000,
    clean: true,
    reconnectPeriod: 2000,
    clientId: clientId,
    will: lwt
  };
  var pub_options = {
    qos: 1,
    retain: true
  };

  let variableTopic = 'workcell/' + clientId + '/variable/';

  console.log('connecting ' + connect_options.clientId);
  client = mqtt.connect('mqtt://localhost:1884', connect_options);
  client.on('close', function() {console.log('client disconnecting ' +
connect_options.clientId)});
  client.on('connect', function(options) {
        console.log(client.id + ' ' + JSON.stringify(options, null, ' '));
        client.publish(lwt.topic, 'online', {qos: lwt.qos, retain: lwt.retain});
        client.subscribe("workcell/#", {qos:1});
        var randInterval = Math.max(Math.ceil(5000 \* Math.random()),200);
        setInterval(function() {
          if(!stopPublishing) {
            client.publish( variableTopic + 'win', JSON.stringify({ item: {
              type: 'int',
              value: i,
              time: new Date
            }}, null, ''), pub_options);
            i++;
          }
        }, randInterval)
      }
  );

  client.on('error', function(error) {
    console.log('error occurred ' + JSON.stringify(error, null, ' '))
  });

  client.on('message', function (topic, message) {
    // message is Buffer
    //console.log('topic ' + topic);
    if (topic.includes('variable')) {
      var zz = JSON.parse(message.toString());
      console.log(topic);
      console.log(JSON.stringify(zz, null, ' '));
    }
  });

  process.on('SIGINT', function() {
    console.log('Got SIGINT');
    client.publish(lwt.topic, 'offline', {qos:1, retain: true});
    stopPublishing = true;
    client.end();
    setTimeout(function(){process.exit()},5000);
  });

On Sat, Jun 4, 2016 at 3:28 PM, Matteo Collina notifications@github.com
wrote:

> Sorry, I'm missing something. It seems the tester spawns a lot of clients
> and sends a lot of messages. Can you reproduce it only with a single client
> (please paste it here in case)?
> 
> Yes, it's probably due to some weird condition, but the current logic is
> sound.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/mcollina/aedes-persistence-level/issues/5#issuecomment-223773635,
> or mute the thread
> https://github.com/notifications/unsubscribe/AGz5ar_6E38MNyiWAofmyC4829UXpDWtks5qIdHzgaJpZM4IqsVk
> .

## 

_. *_.\* _._
- Bruce Blumberg *|  Principal Software Engineer
  *Rethink Robotics, Inc *
  main: 617.500.2487  | cell: 978.430.2206

**Comment by bblumberg** [comment] 2016-06-05 13:15
I've got an interesting hint. If you look at my client (mqtt-test2.js), the
error occurs as a result of the client.publish(lwt...) . I do not see the
error if I subscribe to the topic first. In other words, the error seems to
occur in a context where you are publishing to a retained topic for which
there are no subscribers.

Also to clarify the recent example is just one client who connects, is
disconnected (because of the error) and tries to reconnect until it
eventually reconnects.

Thanks,

bb

p.s. its also ok for you to say that you expect folks to use either memory
based persistence or redis based persistence, and that level based
persistence is not a long term solution.

On Sat, Jun 4, 2016 at 5:25 PM, Bruce Blumberg <
bblumberg@rethinkrobotics.com> wrote:

> Hi
> 
> Yes, I can reproduce it with a single client. Here is the code and I have
> attached it and the code for the broker that I am using...
> 
> Thanks again,
> 
> bb
> 
> /**
> - Created by bblumberg on 6/4/16.
>   */
>   'use strict'
>   var cluster = require('cluster');
>   var mqtt    = require('mqtt');
>   var id = 0;
>   var client = null;
>   var stopPublishing =false;
> 
> let i = 0;
>   id++;
>   var clientId = 'tester' + process.pid;
> 
>   var lwt = {
>     topic: 'workcell/' + clientId + '/status',
>     payload: 'offline',
>     qos: 1,
>     retain: true
>   };
> 
>   var connect_options = {
>     keepalive: 6000,
>     clean: true,
>     reconnectPeriod: 2000,
>     clientId: clientId,
>     will: lwt
>   };
>   var pub_options = {
>     qos: 1,
>     retain: true
>   };
> 
>   let variableTopic = 'workcell/' + clientId + '/variable/';
> 
>   console.log('connecting ' + connect_options.clientId);
>   client = mqtt.connect('mqtt://localhost:1884', connect_options);
>   client.on('close', function() {console.log('client disconnecting ' + connect_options.clientId)});
>   client.on('connect', function(options) {
>         console.log(client.id + ' ' + JSON.stringify(options, null, ' '));
>         client.publish(lwt.topic, 'online', {qos: lwt.qos, retain: lwt.retain});
>         client.subscribe("workcell/#", {qos:1});
>         var randInterval = Math.max(Math.ceil(5000 \* Math.random()),200);
>         setInterval(function() {
>           if(!stopPublishing) {
>             client.publish( variableTopic + 'win', JSON.stringify({ item: {
>               type: 'int',
>               value: i,
>               time: new Date
>             }}, null, ''), pub_options);
>             i++;
>           }
>         }, randInterval)
>       }
>   );
> 
>   client.on('error', function(error) {
>     console.log('error occurred ' + JSON.stringify(error, null, ' '))
>   });
> 
>   client.on('message', function (topic, message) {
>     // message is Buffer
>     //console.log('topic ' + topic);
>     if (topic.includes('variable')) {
>       var zz = JSON.parse(message.toString());
>       console.log(topic);
>       console.log(JSON.stringify(zz, null, ' '));
>     }
>   });
> 
>   process.on('SIGINT', function() {
>     console.log('Got SIGINT');
>     client.publish(lwt.topic, 'offline', {qos:1, retain: true});
>     stopPublishing = true;
>     client.end();
>     setTimeout(function(){process.exit()},5000);
>   });
> 
> On Sat, Jun 4, 2016 at 3:28 PM, Matteo Collina notifications@github.com
> wrote:
> 
> > Sorry, I'm missing something. It seems the tester spawns a lot of clients
> > and sends a lot of messages. Can you reproduce it only with a single client
> > (please paste it here in case)?
> > 
> > Yes, it's probably due to some weird condition, but the current logic is
> > sound.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/mcollina/aedes-persistence-level/issues/5#issuecomment-223773635,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AGz5ar_6E38MNyiWAofmyC4829UXpDWtks5qIdHzgaJpZM4IqsVk
> > .
> 
> ## 
> 
> _. *_.\* _._
> - Bruce Blumberg *|  Principal Software Engineer
>   *Rethink Robotics, Inc *
>   main: 617.500.2487  | cell: 978.430.2206

## 

_. *_.\* _._
- Bruce Blumberg *|  Principal Software Engineer
  *Rethink Robotics, Inc *
  main: 617.500.2487  | cell: 978.430.2206

**Comment by bblumberg** [comment] 2016-06-07 15:26
Hey Matteo

When you get around to looking at this stuff, I am afraid you will also
notice in my test case when a client connects, retained messages that they
subscribe to aren't sent to them. This is consistent across all 3 different
types of persistence. The test case does work with mosca and mosquitto.

I realize this is not your front burner project so I won't bug you further.

bb

On Sun, Jun 5, 2016 at 9:15 AM, Bruce Blumberg <
bblumberg@rethinkrobotics.com> wrote:

> I've got an interesting hint. If you look at my client (mqtt-test2.js),
> the error occurs as a result of the client.publish(lwt...) . I do not see
> the error if I subscribe to the topic first. In other words, the error
> seems to occur in a context where you are publishing to a retained topic
> for which there are no subscribers.
> 
> Also to clarify the recent example is just one client who connects, is
> disconnected (because of the error) and tries to reconnect until it
> eventually reconnects.
> 
> Thanks,
> 
> bb
> 
> p.s. its also ok for you to say that you expect folks to use either memory
> based persistence or redis based persistence, and that level based
> persistence is not a long term solution.
> 
> On Sat, Jun 4, 2016 at 5:25 PM, Bruce Blumberg <
> bblumberg@rethinkrobotics.com> wrote:
> 
> > Hi
> > 
> > Yes, I can reproduce it with a single client. Here is the code and I have
> > attached it and the code for the broker that I am using...
> > 
> > Thanks again,
> > 
> > bb
> > 
> > /**
> > - Created by bblumberg on 6/4/16.
> >   */
> >   'use strict'
> >   var cluster = require('cluster');
> >   var mqtt    = require('mqtt');
> >   var id = 0;
> >   var client = null;
> >   var stopPublishing =false;
> > 
> > let i = 0;
> >   id++;
> >   var clientId = 'tester' + process.pid;
> > 
> >   var lwt = {
> >     topic: 'workcell/' + clientId + '/status',
> >     payload: 'offline',
> >     qos: 1,
> >     retain: true
> >   };
> > 
> >   var connect_options = {
> >     keepalive: 6000,
> >     clean: true,
> >     reconnectPeriod: 2000,
> >     clientId: clientId,
> >     will: lwt
> >   };
> >   var pub_options = {
> >     qos: 1,
> >     retain: true
> >   };
> > 
> >   let variableTopic = 'workcell/' + clientId + '/variable/';
> > 
> >   console.log('connecting ' + connect_options.clientId);
> >   client = mqtt.connect('mqtt://localhost:1884', connect_options);
> >   client.on('close', function() {console.log('client disconnecting ' + connect_options.clientId)});
> >   client.on('connect', function(options) {
> >         console.log(client.id + ' ' + JSON.stringify(options, null, ' '));
> >         client.publish(lwt.topic, 'online', {qos: lwt.qos, retain: lwt.retain});
> >         client.subscribe("workcell/#", {qos:1});
> >         var randInterval = Math.max(Math.ceil(5000 \* Math.random()),200);
> >         setInterval(function() {
> >           if(!stopPublishing) {
> >             client.publish( variableTopic + 'win', JSON.stringify({ item: {
> >               type: 'int',
> >               value: i,
> >               time: new Date
> >             }}, null, ''), pub_options);
> >             i++;
> >           }
> >         }, randInterval)
> >       }
> >   );
> > 
> >   client.on('error', function(error) {
> >     console.log('error occurred ' + JSON.stringify(error, null, ' '))
> >   });
> > 
> >   client.on('message', function (topic, message) {
> >     // message is Buffer
> >     //console.log('topic ' + topic);
> >     if (topic.includes('variable')) {
> >       var zz = JSON.parse(message.toString());
> >       console.log(topic);
> >       console.log(JSON.stringify(zz, null, ' '));
> >     }
> >   });
> > 
> >   process.on('SIGINT', function() {
> >     console.log('Got SIGINT');
> >     client.publish(lwt.topic, 'offline', {qos:1, retain: true});
> >     stopPublishing = true;
> >     client.end();
> >     setTimeout(function(){process.exit()},5000);
> >   });
> > 
> > On Sat, Jun 4, 2016 at 3:28 PM, Matteo Collina notifications@github.com
> > wrote:
> > 
> > > Sorry, I'm missing something. It seems the tester spawns a lot of
> > > clients and sends a lot of messages. Can you reproduce it only with a
> > > single client (please paste it here in case)?
> > > 
> > > Yes, it's probably due to some weird condition, but the current logic is
> > > sound.
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > https://github.com/mcollina/aedes-persistence-level/issues/5#issuecomment-223773635,
> > > or mute the thread
> > > https://github.com/notifications/unsubscribe/AGz5ar_6E38MNyiWAofmyC4829UXpDWtks5qIdHzgaJpZM4IqsVk
> > > .
> > 
> > ## 
> > 
> > _. *_.\* _._
> > - Bruce Blumberg *|  Principal Software Engineer
> >   *Rethink Robotics, Inc *
> >   main: 617.500.2487  | cell: 978.430.2206
> 
> ## 
> 
> _. *_.\* _._
> - Bruce Blumberg *|  Principal Software Engineer
>   *Rethink Robotics, Inc *
>   main: 617.500.2487  | cell: 978.430.2206

## 

_. *_.\* _._
- Bruce Blumberg *|  Principal Software Engineer
  *Rethink Robotics, Inc *
  main: 617.500.2487  | cell: 978.430.2206

**Comment by mcollina** [comment] 2016-06-07 17:03
I still have trouble following your examples and trying to map it to actual errors and cases.

Can you open up an issue on the main repository (https://github.com/mcollina/aedes) if all three persistences suffer from the same issue with an example that replicates that. That example should not include loops, `setInterval`, `setTimeout` or other similar calls to ease reproducibility and the transformation into a regression unit test.

There is something odd about the other persistences and retained messages I presume :(.

**Comment by bblumberg** [comment] 2016-06-07 19:24
Hi

I created a simple test case and posted to the main repository. I got rid
of the loops, setTimeout or setInterval as you suggested.

Yes, persistence isn't working as expected.

Thanks for your patience.

On Tue, Jun 7, 2016 at 1:03 PM, Matteo Collina notifications@github.com
wrote:

> I still have trouble following your examples and trying to map it to
> actual errors and cases.
> 
> Can you open up an issue on the main repository (
> https://github.com/mcollina/aedes) if all three persistences suffer from
> the same issue with an example that replicates that. That example should
> not include loops, setInterval, setTimeout or other similar calls to ease
> reproducibility and the transformation into a regression unit test.
> 
> There is something odd about the other persistences and retained messages
> I presume :(.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/mcollina/aedes-persistence-level/issues/5#issuecomment-224346689,
> or mute the thread
> https://github.com/notifications/unsubscribe/AGz5aqREcAbCDQIFNtcI2asxkmK3Ttftks5qJaR8gaJpZM4IqsVk
> .

## 

_. *_.\* _._
- Bruce Blumberg *|  Principal Software Engineer
  *Rethink Robotics, Inc *
  main: 617.500.2487  | cell: 978.430.2206

**Comment by mcollina** [comment] 2016-06-18 10:06
This should be fixed in the latest Aedes release, feel free to reopen.

**Closed as completed by mcollina** 2016-06-18 10:06 UTC
